title : Blog Title
tagline: Blog Tagline
author :
  name : Recensus
  email : 'develop@recensus.com'
  github : '@recensus'
  twitter : '@rcnss'

navigation :
  - archive.html
  - tags.html
  - categories.html
  - pages.html
  - about.md
  
