title : Recensus:Developer
tagline: Making developing on the Recensus platform a 5 star experiance.
author :
  name : Recensus
  email : 'technical@recensus.com'
  github : '@recensus'
  twitter : '@rcnss'

navigation :
  - archive.html
  - tags.html
  - categories.html
  - pages.html
  - about.md
  
